apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-controller-manager-api-service
  labels:
    control-plane: controller-manager
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiService.type }}
  selector:
    control-plane: controller-manager
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.apiService.ports | toYaml | nindent 2 }}