apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-scanner-viewer-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - scanner.zoltankerezsi.xyz
  resources:
  - scanners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scanner.zoltankerezsi.xyz
  resources:
  - scanners/status
  verbs:
  - get