---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - list
  - watch
- apiGroups:
  - scanner.zoltankerezsi.xyz
  resources:
  - scanners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scanner.zoltankerezsi.xyz
  resources:
  - scanners/finalizers
  verbs:
  - update
- apiGroups:
  - scanner.zoltankerezsi.xyz
  resources:
  - scanners/status
  verbs:
  - get
  - patch
  - update
