apiVersion: batch/v1
kind: Job
metadata:
  name: {{.ScanName}}
  namespace: {{.Namespace}}
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 0
  template:
    spec:
      initContainers:
      - name: grype
        image: anchore/grype:v0.83.0
        env:
          - name: GRYPE_DB_CACHE_DIR
            value: /grype-db
        args:
        - {{.ImageID}}
        - --output
        - cyclonedx-json
        - --file
        - /shared/scan-result.json
        volumeMounts:
        - name: shared
          mountPath: /shared
        - name: grype-db
          mountPath: /grype-db
      containers:
      - name: alpine
        image: alpine/curl:8.10.0
        command: ["sh", "-c"]
        args:
        - |
          echo '{"imageId":"{{.ImageID}}","report":'"$(cat /shared/scan-result.json)"'}\n' > /shared/scan-result.json;
          curl -X PUT -H 'Content-Type: application/json' -d @/shared/scan-result.json {{.ApiServiceHostname}}:8000/scan-results;
        volumeMounts:
        - name: shared
          mountPath: /shared
      restartPolicy: Never
      volumes:
      - name: shared
        emptyDir: {}
      - name: grype-db
        hostPath:
          path: /grype-db